function getInventory()
{
	return  [	{name : 'beds', avail : 150, total : 300, fields : 
					[ 	{name :'male', avail : 50, total : 100},
						{name :'female', avail : 50, total : 100},
						{name :'family', avail : 50, total : 100} ] },
				{name : 'showers', avail : 100, total : 200, fields : 
					[ 	{name :'male', avail : 50, total : 100} ,
						{name :'female', avail : 50, total : 100} ] },
				{name : 'meals', avail : 300, total : 300, fields : 
					[ 	{name :'breakfast', avail : 100, total : 100},
						{name :'lunch', avail : 100, total : 100},
						{name :'dinner', avail : 100, total : 100} ] },
				{name : 'medical', avail : 150, total : 225, fields : 
					[ 	{name :'male', avail : 50, total : 75},
						{name :'female', avail : 50, total : 75},
						{name :'veteran', avail : 50, total : 75} ] },
	 		]
}

module.exports.orgs = [
	{	inv		: getInventory(),
		name 	: 'Glide Memorial',
		addy1 	: '330 Ellis Street',
		addy2 	: '',
		city	: 'San Francisco',
		state 	: 'California',
		phone	: '415.674.6000',
		website	: 'http://glide.org' },
	{	inv		: getInventory(),
		name 	: 'Next Door',
		addy1 	: '1001 Polk Street',
		addy2 	: '',
		city	: 'San Francisco',
		state 	: 'California',
		phone	: '415.292.2180',
		website	: '' },
	{	inv		: getInventory(),
		name 	: 'Episcopal Sanctuary',
		addy1 	: '201 Eighth Street',
		addy2 	: '',
		city	: 'San Francisco',
		state 	: 'California',
		phone	: '415.863.3893',
		website	: '' },
	{	inv		: getInventory(),
		name 	: 'Hospitality House',
		addy1 	: '146 Leavenworth Street',
		addy2 	: '',
		city	: 'San Francisco',
		state 	: 'California',
		phone	: '415.749.2103',
		website	: '' },
	{	inv		: getInventory(),
		name 	: 'Dolores Street - Santa Ana',
		addy1 	: '2909 24th Street',
		addy2 	: '',
		city	: 'San Francisco',
		state 	: 'California',
		phone	: '415.821.2798',
		website	: '' }
]

module.exports.usrs = [
	{	org		: 'Glide Memorial',
		name 	: 'admin',
		pos		: 'admin',
		phone 	: '415-333-3333',
		email	: 'glide@bridge.org',
		passw	: 'sfbridge' },
	{	org		: 'Next Door',
		name 	: 'admin',
		pos		: 'admin',
		phone 	: '415-333-3333',
		email	: 'nextdoor@bridge.org',
		passw	: 'sfbridge' },
	{	org		: 'Episcopal Sanctuary',
		name 	: 'admin',
		pos		: 'admin',
		phone 	: '415-333-3333',
		email	: 'epis@bridge.org',
		passw	: 'sfbridge' },
	{	org		: 'Hospitality House',
		name 	: 'admin',
		pos		: 'admin',
		phone 	: '415-333-3333',
		email	: 'hh@bridge.org',
		passw	: 'sfbridge' },
	{	org		: 'Dolores Street - Santa Ana',
		name 	: 'admin',
		pos		: 'admin',
		phone 	: '415-333-3333',
		email	: 'dolores@bridge.org',
		passw	: 'sfbridge' }
]